FROM ubuntu:latest

RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -y curl

ENV SITE_URL http://google.com/

WORKDIR /data

COPY ./ /opt/project

CMD sh -c "curl -L $SITE_URL > /data/results"
